import net.grinder.util.GrinderUtils

import static net.grinder.script.Grinder.grinder
import static org.junit.Assert.*
import static org.hamcrest.Matchers.*
import net.grinder.plugin.http.HTTPRequest
import net.grinder.plugin.http.HTTPPluginControl
import net.grinder.script.GTest
import net.grinder.script.Grinder
import net.grinder.scriptengine.groovy.junit.GrinderRunner
import net.grinder.scriptengine.groovy.junit.annotation.BeforeProcess
import net.grinder.scriptengine.groovy.junit.annotation.BeforeThread
// import static net.grinder.util.GrinderUtils.* // You can use this if you're using nGrinder after 3.2.3
import org.junit.Before
import org.junit.BeforeClass
import org.junit.Test
import org.junit.runner.RunWith

import java.util.Date
import java.util.List
import java.util.ArrayList

import HTTPClient.Cookie
import HTTPClient.CookieModule
import HTTPClient.HTTPResponse
import HTTPClient.NVPair

import static paramsWaibao.*

/**
 * A simple example using the HTTP plugin that shows the retrieval of a
 * single page via HTTP. 
 * 
 * This script is automatically generated by ngrinder.
 * 
 * @author congcong
 */
@RunWith(GrinderRunner)
class SendMessage {

	public static GTest test
	public static HTTPRequest request
	public static NVPair[] headers = []
	public static NVPair[] params = []
	public static Cookie[] cookies = []

	@BeforeProcess
	public static void beforeProcess() {
		HTTPPluginControl.getConnectionDefaults().timeout = 6000
		test = new GTest(1, "Test1")
		request = new HTTPRequest()
		grinder.logger.info("before process.");
	}

	@BeforeThread 
	public void beforeThread() {
		test.record(this, "test")
		grinder.statistics.delayReports=true;
		grinder.logger.info("before thread.");

	}
	
	@Before
	public void before() {
		request.setHeaders(headers)
		cookies.each { CookieModule.addCookie(it, HTTPPluginControl.getThreadHTTPClientContext()) }
		grinder.logger.info("before thread. init headers and cookies");
	}

	@Test
	public void test(){
		String url = "ws://172.16.39.11:7010";
		ArrayList<String> msgs = new ArrayList<>();
		String accountId = (888888888 + GrinderUtils.threadUniqId*2).toString()
		String oppAccountId = (888888888 + GrinderUtils.threadUniqId*2+1).toString()
		String roomId = accountId+oppAccountId
		msgs.add(enterMessage(accountId,oppAccountId,roomId));
		msgs.add(gobangMessage("READY",-1,-1));
		msgs.add(gobangMessage("STEP",4,7));
		msgs.add(gobangMessage("STEP",5,7));
		msgs.add(gobangMessage("STEP",6,7));
		msgs.add(gobangMessage("STEP",7,7));
		msgs.add(gobangMessage("STEP",8,7));

		ArrayList<String> msgs2 = new ArrayList<>();
		msgs2.add(enterMessage(oppAccountId,accountId,roomId));
		msgs2.add(gobangMessage("READY",-1,-1));
		msgs2.add(gobangMessage("STEP",4,8));
		msgs2.add(gobangMessage("STEP",5,8));
		msgs2.add(gobangMessage("STEP",6,8));
		msgs2.add(gobangMessage("STEP",7,8));
		msgs2.add(gobangMessage("STEP",8,8));
		//System.out.println(msg);
		WebsocketClient websocketClient = new WebsocketClient();
		websocketClient.processRequest(url,msgs,msgs2);

	}
}
